language: ruby
rvm:
- 2.2.0
sudo: false
before_script:
    - git config --global user.email "bouanto@zoho.com"
    - git config --global user.name "Antoni Boucher"
script: bundle exec rake deploy
env:
  global:
    secure: coZ+wNdRjINRL82/knjgH0FFhnVK1pmGJ3V4zkCPXjFuOEhslSZVIn39hbbC6UpX5Rzh+sx7Z3NszmkbE9R/XuqLms/+zavBxZ3KcvVhJkbLVuNfpKyjzu33bayC7dd5hJwPC/DKKELOVVzJ2pYqtYC9+k738TfjqgZh7xI8NoxqLN6J2m/7muci9mUtI74EZoPtn5XBZj6Stw0iGhMFhWSmmwqUTzava6Y51mhf46W54BfCmQ036z5gaMYCTvkNhEryozTlIhs00iXPS6KpCxuruH/nwHjsqzY5YmmzmpmOTZiePd90DATVFIBOfawk8ubza2RZyBj8bGQIuECW8PGO63aIik8A+K8SrCYyB9483qNYgehi7UacdcZzo4EcZpUro/w7FOJDbcyauOQ0mPc4/4NOojgwEWY5cheYcEyWXb0akfGDhukerzz3J/qWUzVdR2H4VyZAQEvROj2oOUGis8HJXm9CinwY68D6vH65XBSNHhB/q8vRnrl4WQdkgYCZUnxTAl07jPsXvwMj1RIe2VJUi37XSZFh0yptz1jX8r+VOGayHautftkfgW5WiLZxsZMRDxH0FjNBNrljSTwFA3P52q+Sc6V+CBrlJs7+mm21wi+RBT2P2WzDdyJ0aKsGyKs586jXha2YjBb1JFna5h+NsjF/C9ZeKMioDgA=
